
services:
  web:
    build: .
    image: capstone-portfolio-web
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:?DJANGO_SECRET_KEY is required}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-0.0.0.0,localhost,web,nginx}
      DJANGO_STATIC_ROOT: /vol/web/static
      DJANGO_MEDIA_ROOT: /vol/web/media
      DJANGO_LOG_LEVEL: ${DJANGO_LOG_LEVEL:-INFO}
      POSTGRES_DB: ${POSTGRES_DB:-capstone}
      POSTGRES_USER: ${POSTGRES_USER:-capstone}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-capstone}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-capstone}
      POSTGRES_USER: ${POSTGRES_USER:-capstone}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-capstone}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - static_data:/vol/web/static:ro
      - media_data:/vol/web/media:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
  media_data:
